### PR TITLE
Personalize model table builder

### PR DESCRIPTION
**Pull request by WimCartago**
Personalize model table builder for use where with field, operator and
comparator....

### CODE REVIEW

**Comment by joselfonseca** [comment]
This would not need the model included in the PR. Could you please explain the goal of this modification? I don't quite get it.

**Comment by WimCartago** [comment]
extract data from model using parameteres 
example stract code:
------------------------------------------------------------------------------------
 $data = $prueba->view_balance('edad', '<=', 10);
    
           return view('balance/balance')
               ->with('table', $table->renderData(   $data   )) 
-------------------------------------------------------------------------------------

**Comment by joselfonseca** [comment]
That is already supported, you can filter the model how ever you want before it calls the render method. say you have a model like this:

```
$model = new Model();
$model->whereHas('relation', function($q){
    $q->whereIn('id', ['1','2']);
});
$model->where('field', 'value')->orderBy('field', 'ASC');
```
once you set all the constrains in your model, you can set it in the table builder

```
$builder->setModel($model)->render();
```
Besides, doing it the proposed way, only one `where` constrain can be set.

**Comment by WimCartago** [comment]
ok.

**Comment by joselfonseca** [comment]
Thanks for the input. do not hesitate to send more proposals if you think is necessary. 

Happy Coding!

**Pull request closed without merging**
